language: go

go:
  - 1.7

sudo: false

install:
  - go get -u -v github.com/spf13/hugo

script:
- hugo

# Deploy to GitHub pages
deploy:
  repo: pmbaumgartner/pmbaumgartner.github.io
  target_branch: master
  skip_cleanup: true
  local_dir: public
  keep-history: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  name: pmbaumgartner
  on:
    branch: master
